# Generated by Django 2.2.9 on 2023-02-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230214_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True, upload_to='posts/', verbose_name='картинка'
            ),
        ),
    ]
