# Generated by Django 2.2.9 on 2023-02-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20230216_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
